services:
  - type: web
    name: ojas-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        sync: false
